server:
  port: 8080

spring:
  mvc:
    converters:
      preferred-json-mapper: jackson
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        format_sql: true
        jdbc:
          batch_size: 1000
          fetch_size: 1000
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/orders-management
    username: postgres
    password: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-interval: 5s
          max-attempts: 3
          multiplier: '2'



